// Pure logic for the common server guard (entrega-1-contratos.md §2).
//
// ZERO imports on purpose: this is the part `deno test` can load without
// network access (`deno.land`/`jsr.io` are blocked in the sandbox — same
// lesson as StockFlow's `machinery_sales_fields_test.ts`). Everything here
// is a plain function/class over plain data — no `npm:@base44/sdk`, no
// `Request`/`Response`, no I/O.
//
// `_guard.ts` (same directory after `npm run generate:guards` copies both
// files) imports this file and adds the network-facing parts: reading the
// real `User`/`WineBar`/`PermissionProfile` rows and building the `Ctx`.
//
// CANONICAL SOURCE — do not hand-edit this file's PERMISSION_DEFAULTS block.
// It is regenerated by `scripts/generate-guards.mjs` from
// `src/lib/permissionRegistry.js`, which is the single source of truth.
// `npm run check:guards` fails the build if this drifts from that registry.

// AUTOGEN:PERMISSION_DEFAULTS:BEGIN — generado por scripts/generate-guards.mjs
// desde src/lib/permissionRegistry.js. No editar a mano.
export const PERMISSION_DEFAULTS: Record<string, { bar_admin: boolean; staff: boolean }> = {
  "Menú:ver": { bar_admin: true, staff: true },
  "Menú:editar": { bar_admin: true, staff: false },
  "Menú:ver_costos": { bar_admin: true, staff: false },
  "Mesas:editar": { bar_admin: true, staff: false },
  "Comandas:tomar": { bar_admin: true, staff: true },
  "Comandas:cancelar_enviado": { bar_admin: true, staff: true },
  "Comandas:mover_mesas": { bar_admin: true, staff: true },
  "Comandas:cancelar_orden": { bar_admin: true, staff: false },
  "Estaciones:cocina": { bar_admin: true, staff: true },
  "Estaciones:barra": { bar_admin: true, staff: true },
  "Cobro:cobrar": { bar_admin: true, staff: true },
  "Cobro:descuento": { bar_admin: true, staff: false },
  "Cobro:anular_pago": { bar_admin: true, staff: false },
  "Turno:operar": { bar_admin: true, staff: true },
  "Turno:ver_corte": { bar_admin: true, staff: false },
  "Inventario:ver": { bar_admin: true, staff: true },
  "Inventario:merma": { bar_admin: true, staff: true },
  "Inventario:editar": { bar_admin: true, staff: false },
  "Impresion:operar": { bar_admin: true, staff: true },
  "Reportes:ver": { bar_admin: true, staff: false },
  "Ajustes:editar": { bar_admin: true, staff: false },
  "Ajustes:exportar": { bar_admin: true, staff: false },
  "Equipo:invitar": { bar_admin: true, staff: false },
  "Equipo:cambiar_rol": { bar_admin: true, staff: false },
  "Equipo:quitar": { bar_admin: true, staff: false },
  "Asistencia:checar": { bar_admin: true, staff: true },
  "Asistencia:ver_equipo": { bar_admin: true, staff: false },
  "Asistencia:corregir": { bar_admin: true, staff: false },
  "Seguridad:ver": { bar_admin: true, staff: false },
};
// AUTOGEN:PERMISSION_DEFAULTS:END

export type AppRole = 'bar_admin' | 'staff';

export interface PermissionResolveCtx {
  isPlatform: boolean;
  appRole: AppRole | null | undefined;
  /** The role's PermissionProfile overrides. */
  overrides?: Record<string, boolean> | null;
  /** What the bar admin decided for THIS person (User.permission_overrides). */
  personOverrides?: Record<string, boolean> | null;
}

/**
 * Keys that replaced an older one: a profile or a person saved with the old
 * key keeps applying to the new ones (2026-10-06: `Estaciones:operar` split
 * into cocina and barra). Same map in src/lib/permissionRegistry.js.
 */
export const LEGACY_PERMISSION_ALIASES: Record<string, string> = {
  'Estaciones:cocina': 'Estaciones:operar',
  'Estaciones:barra': 'Estaciones:operar',
};

/** A User row's per-person overrides, or null when absent or not a plain map. */
export function personOverridesOf(row: { permission_overrides?: unknown } | null | undefined): Record<string, boolean> | null {
  const raw = row?.permission_overrides;
  return raw && typeof raw === 'object' && !Array.isArray(raw) ? (raw as Record<string, boolean>) : null;
}

function overrideFor(map: Record<string, boolean> | null | undefined, key: string): boolean | undefined {
  if (!map || typeof map !== 'object') return undefined;
  if (Object.prototype.hasOwnProperty.call(map, key)) return !!map[key];
  const legacy = LEGACY_PERMISSION_ALIASES[key];
  if (legacy && Object.prototype.hasOwnProperty.call(map, legacy)) return !!map[legacy];
  return undefined;
}

/**
 * Same precedence documented in the contract's §2 for `hasPermission`:
 * platform / bar_admin → always allowed; else an explicit PermissionProfile
 * override for the caller's role; else the registry default; an unknown key
 * (not in PERMISSION_DEFAULTS at all) denies rather than guessing.
 */
export function resolvePermission(key: string, ctx: PermissionResolveCtx): boolean {
  if (ctx.isPlatform || ctx.appRole === 'bar_admin') return true;
  const person = overrideFor(ctx.personOverrides, key);
  if (person !== undefined) return person;
  const role = overrideFor(ctx.overrides, key);
  if (role !== undefined) return role;
  const def = PERMISSION_DEFAULTS[key];
  if (!def) return false; // unknown key => deny
  if (ctx.appRole === 'staff') return !!def.staff;
  return false; // no app_role at all => deny
}

/**
 * Module 14: a request with no tenant is refused (403 `no_tenant`) unless the
 * caller is the platform admin AND the route explicitly opted in with
 * `allowNoTenant(route)` (today only `catalog.importMenu`). Before 2026-09-29
 * the router opted EVERY route in and a platform caller with no bar slipped
 * past this check on all of them; the decision now lives here, pure, so the
 * tests pin it. A tenant user always passes (the tenant is theirs).
 */
export function tenantAccessDenied(input: {
  tenantId: string | null | undefined;
  isPlatform: boolean;
  routeAllowsNoTenant: boolean;
}): boolean {
  if (input.tenantId) return false;
  return !(input.isPlatform && input.routeAllowsNoTenant);
}

/** True when a route function carries the opt-in mark set by `allowNoTenant()`. */
export function routeAllowsNoTenant(route: unknown): boolean {
  return typeof route === 'function' && (route as { allowNoTenant?: unknown }).allowNoTenant === true;
}

// WineBar.billing_status values that block writes (§ "requireWritable").
const BLOCKED_BILLING_STATUSES = new Set(['view_only', 'suspended']);

export function isBlockedBillingStatus(billingStatus: string | null | undefined): boolean {
  return !!billingStatus && BLOCKED_BILLING_STATUSES.has(billingStatus);
}

/**
 * Ownership check used by `_guard.ts`'s `loadOwned`: a row belongs to the
 * caller's tenant when the caller is platform, or the row's OWN `tenant_id`
 * (rows come back FLAT from the Base44 SDK — see module 22's note in
 * `_guard.ts` — never `row.data.tenant_id`) matches `ctx.tenantId`. Pulled
 * out here, pure, so `deno test` can pin this exact comparison: fixed
 * 2026-09-28, this used to read `row.data?.tenant_id`, which is `undefined`
 * on every real (flat) row — for a non-platform caller that made EVERY
 * row read as belonging to no tenant, so `loadOwned` 404'd on every id
 * (including the caller's own bar's rows) the moment a real row reached it.
 */
export function rowBelongsToTenant(
  row: ({ tenant_id?: string | null } & Record<string, unknown>) | null | undefined,
  tenantId: string | null,
  isPlatform: boolean
): boolean {
  if (isPlatform) return true;
  return !!row && row.tenant_id === tenantId;
}

// A typed error the router (`handle`) maps to an HTTP response. Deliberately
// a plain class with no imports, so the pure logic above can throw it too
// and the unit tests can assert on `.status`/`.code` without touching the
// network-facing `_guard.ts`.
/**
 * True when an error thrown by the Base44 SDK is the platform's rate limit
 * (seen live 2026-09-28 as a plain "Rate limit exceeded" message). `handle()`
 * maps it to 429 with a Spanish message instead of a 500 in English.
 */
export function isRateLimitError(error: unknown): boolean {
  const e = error as any;
  const status = e?.status ?? e?.response?.status;
  if (status === 429) return true;
  const message = typeof e?.message === 'string' ? e.message : '';
  return /rate limit/i.test(message);
}

export class HttpError extends Error {
  status: number;
  code: string;
  // Optional structured fields merged into the JSON error body by handle()
  // (e.g. `{ order_id }` on 409 'table_busy' — contract §4: "mesa ocupada ->
  // 409 table_busy con order_id existente"). Never overrides `error`/`code`
  // even if a caller's `extra` happens to carry those keys.
  extra?: Record<string, unknown>;
  constructor(status: number, code: string, message: string, extra?: Record<string, unknown>) {
    super(message);
    this.status = status;
    this.code = code;
    this.extra = extra;
  }
}

// ---- Money helpers (plan-tecnico.md §5: money is integer centavos, only
// the server computes it). Kept here — not in src/lib/money.js — because
// these are the ones the *_logic.ts of each feature agent will reuse to
// validate/sum amounts server-side, and that file must stay import-free too.

/** True for a value that is safe to store/compare as an integer centavos amount. */
export function isValidCents(value: unknown): value is number {
  return typeof value === 'number' && Number.isInteger(value) && Number.isFinite(value) && value >= 0;
}

/** Sums an array of integer-centavos amounts, throwing on anything invalid. */
export function sumCents(values: number[]): number {
  return values.reduce((total, v) => {
    if (!isValidCents(v)) throw new HttpError(400, 'invalid_amount', 'Monto inválido');
    return total + v;
  }, 0);
}

/** unit_price (cents) * qty, rounded to the nearest centavo (qty may be fractional, e.g. granel by weight). */
export function lineTotalCents(unitPriceCents: number, qty: number): number {
  if (!isValidCents(unitPriceCents)) throw new HttpError(400, 'invalid_amount', 'Precio inválido');
  if (typeof qty !== 'number' || !Number.isFinite(qty) || qty <= 0) {
    throw new HttpError(400, 'invalid_qty', 'Cantidad inválida');
  }
  return Math.round(unitPriceCents * qty);
}

export function pesosToCents(pesos: number): number {
  return Math.round(pesos * 100);
}

export function centsToPesos(cents: number): number {
  return cents / 100;
}

// ---- Cost redaction (D7, entrega-1-contratos.md §4/§6b) ----
//
// `OrderItem.unit_cost` is frozen server-side at addItems time and RLS
// already blocks direct reads of it to non-platform callers
// (OrderItem.jsonc: `properties.unit_cost.rls.read`), but every `orders`/
// `stations` handler that RETURNS an OrderItem row does so through the
// function's own JSON response, which RLS never touches — a handler that
// forgets to redact hands `unit_cost` to every caller regardless of
// `Menú:ver_costos`, exactly like `catalog.listProducts` already guards
// against for `Product.cost`/`variants[].cost`. These two pure helpers are
// the one place that redaction logic lives, so every handler that returns
// OrderItem row(s) calls `hasPermission(ctx, 'Menú:ver_costos')` once and
// pipes its result (row or row[]) through here before responding.

/** Removes `unit_cost` from a single OrderItem-shaped row unless `canSeeCosts`. */
export function redactItemCost<T extends Record<string, unknown>>(row: T, canSeeCosts: boolean): T {
  if (canSeeCosts || row == null) return row;
  const { unit_cost: _unit_cost, ...rest } = row;
  return rest as T;
}

/** Array variant of {@link redactItemCost}. */
export function redactItemCosts<T extends Record<string, unknown>>(rows: T[], canSeeCosts: boolean): T[] {
  if (canSeeCosts) return rows;
  return rows.map((row) => redactItemCost(row, canSeeCosts));
}

// ---- Entrega 2 shared pure logic (entrega-2-contratos.md §1, §4) ----
//
// Lives in the template so `orders` and `payments` (and shifts/reports/
// printing) compute exactly the same numbers from one copy.

/** Aguascalientes (Zona Centro) is UTC-6 all year: Mexico dropped DST in 2022. */
export const BAR_UTC_OFFSET_MIN = -360;

export interface PaymentMethodDef {
  key: string;
  label: string;
  is_cash: boolean;
  active: boolean;
}

/** Used whenever a WineBar has no `payment_methods` yet (contract §0). */
export const DEFAULT_PAYMENT_METHODS: PaymentMethodDef[] = [
  { key: 'efectivo', label: 'Efectivo', is_cash: true, active: true },
  { key: 'tarjeta', label: 'Tarjeta', is_cash: false, active: true },
  { key: 'transferencia', label: 'Transferencia', is_cash: false, active: true },
];

export interface TotalsItemLike {
  status?: string | null;
  unit_price?: number | null;
  qty?: number | null;
}

export interface TotalsOptions {
  discount_kind?: 'descuento' | 'cortesia' | null;
  discount_pct?: number | null;
  discount?: number | null;
  tip_pct?: number | null;
  tip?: number | null;
}

export interface OrderTotals {
  subtotal: number;
  discount: number;
  tip: number;
  total: number;
}

function isPct(v: unknown): v is number {
  return typeof v === 'number' && Number.isFinite(v) && v >= 0;
}

/**
 * subtotal = Σ round(unit_price*qty) over non-cancelled lines.
 * discount: cortesia -> whole subtotal; discount_pct -> round(subtotal*pct/100)
 * (capped at subtotal); otherwise min(discount, subtotal).
 * tip: tip_pct -> round((subtotal - discount)*pct/100); otherwise tip ?? 0.
 * total = subtotal - discount + tip.
 */
export function computeOrderTotals(items: TotalsItemLike[], opts: TotalsOptions = {}): OrderTotals {
  const subtotal = (items ?? []).reduce((sum, item) => {
    if (item.status === 'cancelado') return sum;
    const qty = typeof item.qty === 'number' && item.qty > 0 ? item.qty : 0;
    const price = typeof item.unit_price === 'number' ? item.unit_price : 0;
    return sum + Math.round(price * qty);
  }, 0);

  let discount: number;
  if (opts.discount_kind === 'cortesia') {
    discount = subtotal;
  } else if (isPct(opts.discount_pct)) {
    discount = Math.min(subtotal, Math.round((subtotal * opts.discount_pct) / 100));
  } else {
    const raw = typeof opts.discount === 'number' && Number.isFinite(opts.discount) ? opts.discount : 0;
    discount = Math.min(Math.max(0, Math.round(raw)), subtotal);
  }

  let tip: number;
  if (isPct(opts.tip_pct)) {
    tip = Math.round(((subtotal - discount) * opts.tip_pct) / 100);
  } else {
    const raw = typeof opts.tip === 'number' && Number.isFinite(opts.tip) ? opts.tip : 0;
    tip = Math.max(0, Math.round(raw));
  }

  return { subtotal, discount, tip, total: subtotal - discount + tip };
}

/** Σ amount of payments that are not voided. */
export function activePaymentsTotal(payments: Array<{ amount?: number | null; voided_at?: string | null }>): number {
  return (payments ?? []).reduce((sum, p) => (p.voided_at ? sum : sum + (typeof p.amount === 'number' ? p.amount : 0)), 0);
}

/**
 * Idempotency survivor: the row with the oldest `created_date` (id breaks
 * ties). Every concurrent caller picks the same winner. Null for no rows.
 */
export function pickSurvivor<T extends { id?: string | null; created_date?: string | null }>(rows: T[]): T | null {
  if (!rows || rows.length === 0) return null;
  return [...rows].sort((a, b) => {
    const da = a.created_date ? Date.parse(a.created_date) : Infinity;
    const db = b.created_date ? Date.parse(b.created_date) : Infinity;
    if (da !== db) return da < db ? -1 : 1;
    const ia = String(a.id ?? '');
    const ib = String(b.id ?? '');
    return ia < ib ? -1 : ia > ib ? 1 : 0;
  })[0];
}

/**
 * "concept ... amount" line of exactly `width` columns (default 32, 58 mm
 * paper). Truncates `left` when it does not fit; always keeps one space.
 */
export function padLine(left: string, right: string, width = 32): string {
  const l = String(left ?? '');
  const r = String(right ?? '');
  if (r.length >= width) return r.slice(0, width);
  const room = width - r.length - 1;
  const cut = l.length > room ? l.slice(0, room) : l;
  return cut + ' '.repeat(width - cut.length - r.length) + r;
}

/**
 * UTC bounds of a local calendar day: `fromISO` is local 00:00 inclusive,
 * `toISO` is the NEXT local midnight, exclusive ([from, to)).
 */
export function localDayRange(dateStr: string): { fromISO: string; toISO: string } {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(String(dateStr ?? ''));
  if (!m) throw new HttpError(400, 'invalid_date', 'Fecha inválida');
  const y = Number(m[1]);
  const mo = Number(m[2]);
  const d = Number(m[3]);
  const startUtc = Date.UTC(y, mo - 1, d);
  const check = new Date(startUtc);
  if (check.getUTCFullYear() !== y || check.getUTCMonth() !== mo - 1 || check.getUTCDate() !== d) {
    throw new HttpError(400, 'invalid_date', 'Fecha inválida');
  }
  const from = startUtc - BAR_UTC_OFFSET_MIN * 60_000;
  return { fromISO: new Date(from).toISOString(), toISO: new Date(from + 86_400_000).toISOString() };
}

/** Local calendar date 'YYYY-MM-DD' of an instant. */
export function localDateString(iso: string): string {
  const t = Date.parse(iso);
  if (Number.isNaN(t)) throw new HttpError(400, 'invalid_date', 'Fecha inválida');
  return new Date(t + BAR_UTC_OFFSET_MIN * 60_000).toISOString().slice(0, 10);
}

/** Local hour 0-23 of an instant. */
export function localHour(iso: string): number {
  const t = Date.parse(iso);
  if (Number.isNaN(t)) throw new HttpError(400, 'invalid_date', 'Fecha inválida');
  return new Date(t + BAR_UTC_OFFSET_MIN * 60_000).getUTCHours();
}

/** Splits integer centavos into `parts` shares; leftover centavos go to the first shares. */
export function splitEqual(amount: number, parts: number): number[] {
  if (!Number.isInteger(amount) || amount < 0) throw new HttpError(400, 'invalid_amount', 'Monto inválido');
  if (!Number.isInteger(parts) || parts < 1) throw new HttpError(400, 'invalid_parts', 'Número de partes inválido');
  const base = Math.floor(amount / parts);
  const rest = amount - base * parts;
  return Array.from({ length: parts }, (_, i) => base + (i < rest ? 1 : 0));
}

// ---------------------------------------------------------------------------
// Terminal mode (docs/modo-terminal-diseno.md, phase 2a).
//
// A terminal is a device the bar_admin authorized. It signs in to Base44 as
// its own account (User.app_role 'terminal', no permissions of its own). A
// person unlocks it with their PIN and gets a short "pass" signed with that
// device's own key; every call from the terminal carries the pass, and the
// guard then acts AS that person. Without a valid pass the terminal can only
// run the routes marked `allowLockedTerminal` (who am I, unlock).
// ---------------------------------------------------------------------------

export const TERMINAL_APP_ROLE = 'terminal';
export const PASS_TTL_MS = 15 * 60_000;
/** Bar roles a person must hold to work at a terminal. */
export const TERMINAL_PERSON_ROLES = new Set(['bar_admin', 'staff']);

function hexOf(bytes: Uint8Array): string {
  let out = '';
  for (const b of bytes) out += b.toString(16).padStart(2, '0');
  return out;
}

function b64urlEncode(text: string): string {
  let bin = '';
  for (const b of new TextEncoder().encode(text)) bin += String.fromCharCode(b);
  return btoa(bin).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

function b64urlDecode(text: string): string {
  const bin = atob(text.replace(/-/g, '+').replace(/_/g, '/') + '==='.slice((text.length + 3) % 4));
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return new TextDecoder().decode(bytes);
}

async function hmacHex(keyHex: string, message: string): Promise<string> {
  const keyBytes = new Uint8Array(keyHex.length / 2);
  for (let i = 0; i < keyBytes.length; i++) keyBytes[i] = parseInt(keyHex.slice(i * 2, i * 2 + 2), 16);
  const key = await crypto.subtle.importKey('raw', keyBytes, { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
  return hexOf(new Uint8Array(await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(message))));
}

function timingSafeEqualStr(a: string, b: string): boolean {
  let diff = a.length ^ b.length;
  const len = Math.max(a.length, b.length);
  for (let i = 0; i < len; i++) diff |= (a.charCodeAt(i) || 0) ^ (b.charCodeAt(i) || 0);
  return diff === 0;
}

/** A fresh random key or id, hex. */
export function randomHex(bytes: number): string {
  return hexOf(crypto.getRandomValues(new Uint8Array(bytes)));
}

/**
 * Signs a pass for `userId` on `deviceId`, valid until `expMs`. `epoch` is the
 * device's `pass_epoch`: every unlock and every lock bumps it, so the pass of
 * whoever used the terminal before stops working at once instead of living
 * out its 15 minutes.
 */
export async function signPass(keyHex: string, deviceId: string, userId: string, expMs: number, epoch: number): Promise<string> {
  const payload = b64urlEncode(JSON.stringify({ d: deviceId, u: userId, e: expMs, n: epoch }));
  return `${payload}.${await hmacHex(keyHex, payload)}`;
}

/**
 * The person a pass names, or null when it is malformed, signed with another
 * key, for another device, or expired. Never throws.
 */
export async function verifyPass(
  keyHex: unknown,
  deviceId: string,
  pass: unknown,
  nowMs: number,
  epoch: number
): Promise<{ userId: string; expMs: number } | null> {
  if (typeof keyHex !== 'string' || !/^[0-9a-f]{64}$/.test(keyHex)) return null;
  if (typeof pass !== 'string' || pass.length > 2048) return null;
  const dot = pass.indexOf('.');
  if (dot <= 0) return null;
  const payload = pass.slice(0, dot);
  const sig = pass.slice(dot + 1);
  try {
    if (!timingSafeEqualStr(await hmacHex(keyHex, payload), sig)) return null;
    const data = JSON.parse(b64urlDecode(payload));
    if (data?.d !== deviceId || typeof data?.u !== 'string' || !data.u) return null;
    if (typeof data?.e !== 'number' || data.e <= nowMs) return null;
    if (data?.n !== epoch) return null;
    return { userId: data.u, expMs: data.e };
  } catch {
    return null;
  }
}

/** Who may use a terminal: `{mode:'all'}` (default) or `{mode:'people', user_ids}`. */
export function terminalAllows(allowed: unknown, userId: string): boolean {
  const a = allowed as { mode?: unknown; user_ids?: unknown } | null | undefined;
  if (!a || a.mode !== 'people') return true;
  return Array.isArray(a.user_ids) && a.user_ids.includes(userId);
}

/** Whether `person` may work at `device`: same bar, a bar role, and on its list. */
export function personMayUseTerminal(
  person: { id?: string; tenant_id?: string | null; app_role?: string | null } | null | undefined,
  device: { tenant_id?: string | null; allowed?: unknown } | null | undefined
): boolean {
  if (!person?.id || !device?.tenant_id) return false;
  if (person.tenant_id !== device.tenant_id) return false;
  if (!TERMINAL_PERSON_ROLES.has(String(person.app_role ?? ''))) return false;
  return terminalAllows(device.allowed, person.id);
}

/** The device's current pass epoch (missing on rows from before it existed = 0). */
export function passEpochOf(device: { pass_epoch?: unknown } | null | undefined): number {
  const n = device?.pass_epoch;
  return Number.isInteger(n) && (n as number) >= 0 ? (n as number) : 0;
}

/**
 * A terminal nobody unlocked may still run its print station (it prints by
 * device, not by person) and its checador (each person punches with THEIR own
 * PIN, so nobody needs to unlock the terminal just to clock in; José,
 * 2026-10-06). Nothing else.
 */
export const LOCKED_TERMINAL_PERMISSIONS = new Set(['Impresion:operar', 'Asistencia:checar']);

/** True when a route function carries the mark set by `allowLockedTerminal()`. */
export function routeAllowsLockedTerminal(route: unknown): boolean {
  return typeof route === 'function' && (route as { allowLockedTerminal?: unknown }).allowLockedTerminal === true;
}

// ---------------------------------------------------------------------------
// People's names. Base44 never lets an account change `full_name` after it
// signs up (and Sommel's signup did not ask for it), so Sommel keeps its own
// `User.display_name`. Every screen and every "who did it" uses this order.
// Same rule in manageStaff/_member_logic.ts and createWineBar/_trial_logic.ts
// (they cannot import this file); base44/tests/display_name_test.ts pins them.
// ---------------------------------------------------------------------------

/** display_name, then full_name, then the part of the email before the @. */
export function personName(
  user: { display_name?: string | null; full_name?: string | null; email?: string | null } | null | undefined
): string {
  const own = String(user?.display_name ?? '').trim();
  if (own) return own;
  const full = String(user?.full_name ?? '').trim();
  if (full) return full;
  const email = String(user?.email ?? '').trim();
  const at = email.indexOf('@');
  return (at > 0 ? email.slice(0, at) : email) || 'Sin nombre';
}

/** A name as stored: trimmed, single spaces, 1 to 60 characters, no control
 *  characters. Returns null when it is not a usable name. */
export function normalizeDisplayName(input: unknown): string | null {
  if (typeof input !== 'string') return null;
  // deno-lint-ignore no-control-regex
  const v = input.replace(/[\u0000-\u001f\u007f]/g, '').trim().replace(/\s+/g, ' ');
  return v.length >= 1 && v.length <= 60 ? v : null;
}

// ---- Short read cache (concurrency, 2026-10-06) ----
// Base44 rate-limits entity operations per app. Every guarded call used to
// re-read the bar (WineBar) and, for staff, its PermissionProfile. Both now
// live up to CACHE_TTL_MS in the warm function instance. Decided by José:
// a permission change or a license suspension may take up to 20 s to apply.
// The User row and the TerminalDevice are NEVER cached: removing someone or
// revoking a terminal takes effect on the next call.
export const CACHE_TTL_MS = 20_000;
export const CACHE_MAX_ENTRIES = 500;

export class TtlCache<V> {
  private map = new Map<string, { value: V; exp: number }>();
  constructor(private ttlMs = CACHE_TTL_MS, private max = CACHE_MAX_ENTRIES) {}

  /** The value, or undefined when missing or older than the TTL. */
  get(key: string, nowMs: number): V | undefined {
    const hit = this.map.get(key);
    if (!hit) return undefined;
    if (hit.exp <= nowMs) {
      this.map.delete(key);
      return undefined;
    }
    return hit.value;
  }

  set(key: string, value: V, nowMs: number): void {
    this.map.delete(key);
    if (this.map.size >= this.max) {
      const oldest = this.map.keys().next().value;
      if (oldest !== undefined) this.map.delete(oldest);
    }
    this.map.set(key, { value, exp: nowMs + this.ttlMs });
  }

  /** Drops one key, or every key starting with `prefix` when it ends in '|'. */
  delete(keyOrPrefix: string): void {
    if (!keyOrPrefix.endsWith('|')) {
      this.map.delete(keyOrPrefix);
      return;
    }
    for (const k of [...this.map.keys()]) if (k.startsWith(keyOrPrefix)) this.map.delete(k);
  }

  get size(): number {
    return this.map.size;
  }
}

/** Cache key of a tenant+role permission profile. */
export function profileKey(tenantId: string, role: string): string {
  return `${tenantId}|${role}`;
}

/** Whether a route asked to read the bar and permissions fresh (Ajustes, Cuenta, Permisos). */
export function routeWantsFresh(route: unknown): boolean {
  return typeof route === 'function' && (route as { freshReads?: unknown }).freshReads === true;
}
