// Pure logic for the common server guard (entrega-1-contratos.md §2).
//
// ZERO imports on purpose: this is the part `deno test` can load without
// network access (`deno.land`/`jsr.io` are blocked in the sandbox — same
// lesson as StockFlow's `machinery_sales_fields_test.ts`). Everything here
// is a plain function/class over plain data — no `npm:@base44/sdk`, no
// `Request`/`Response`, no I/O.
//
// `_guard.ts` (same directory after `npm run generate:guards` copies both
// files) imports this file and adds the network-facing parts: reading the
// real `User`/`WineBar`/`PermissionProfile` rows and building the `Ctx`.
//
// CANONICAL SOURCE — do not hand-edit this file's PERMISSION_DEFAULTS block.
// It is regenerated by `scripts/generate-guards.mjs` from
// `src/lib/permissionRegistry.js`, which is the single source of truth.
// `npm run check:guards` fails the build if this drifts from that registry.

// AUTOGEN:PERMISSION_DEFAULTS:BEGIN — generado por scripts/generate-guards.mjs
// desde src/lib/permissionRegistry.js. No editar a mano.
export const PERMISSION_DEFAULTS: Record<string, { bar_admin: boolean; staff: boolean }> = {
  "Menú:ver": { bar_admin: true, staff: true },
  "Menú:editar": { bar_admin: true, staff: false },
  "Menú:ver_costos": { bar_admin: true, staff: false },
  "Mesas:editar": { bar_admin: true, staff: false },
  "Comandas:tomar": { bar_admin: true, staff: true },
  "Comandas:cancelar_enviado": { bar_admin: true, staff: true },
  "Comandas:mover_mesas": { bar_admin: true, staff: true },
  "Comandas:cancelar_orden": { bar_admin: true, staff: false },
  "Estaciones:operar": { bar_admin: true, staff: true },
};
// AUTOGEN:PERMISSION_DEFAULTS:END

export type AppRole = 'bar_admin' | 'staff';

export interface PermissionResolveCtx {
  isPlatform: boolean;
  appRole: AppRole | null | undefined;
  overrides?: Record<string, boolean> | null;
}

/**
 * Same precedence documented in the contract's §2 for `hasPermission`:
 * platform / bar_admin → always allowed; else an explicit PermissionProfile
 * override for the caller's role; else the registry default; an unknown key
 * (not in PERMISSION_DEFAULTS at all) denies rather than guessing.
 */
export function resolvePermission(key: string, ctx: PermissionResolveCtx): boolean {
  if (ctx.isPlatform || ctx.appRole === 'bar_admin') return true;
  const overrides = ctx.overrides || {};
  if (Object.prototype.hasOwnProperty.call(overrides, key)) return !!overrides[key];
  const def = PERMISSION_DEFAULTS[key];
  if (!def) return false; // unknown key => deny
  if (ctx.appRole === 'staff') return !!def.staff;
  return false; // no app_role at all => deny
}

// WineBar.billing_status values that block writes (§ "requireWritable").
const BLOCKED_BILLING_STATUSES = new Set(['view_only', 'suspended']);

export function isBlockedBillingStatus(billingStatus: string | null | undefined): boolean {
  return !!billingStatus && BLOCKED_BILLING_STATUSES.has(billingStatus);
}

/**
 * Ownership check used by `_guard.ts`'s `loadOwned`: a row belongs to the
 * caller's tenant when the caller is platform, or the row's OWN `tenant_id`
 * (rows come back FLAT from the Base44 SDK — see module 22's note in
 * `_guard.ts` — never `row.data.tenant_id`) matches `ctx.tenantId`. Pulled
 * out here, pure, so `deno test` can pin this exact comparison: fixed
 * 2026-09-28, this used to read `row.data?.tenant_id`, which is `undefined`
 * on every real (flat) row — for a non-platform caller that made EVERY
 * row read as belonging to no tenant, so `loadOwned` 404'd on every id
 * (including the caller's own bar's rows) the moment a real row reached it.
 */
export function rowBelongsToTenant(
  row: ({ tenant_id?: string | null } & Record<string, unknown>) | null | undefined,
  tenantId: string | null,
  isPlatform: boolean
): boolean {
  if (isPlatform) return true;
  return !!row && row.tenant_id === tenantId;
}

// A typed error the router (`handle`) maps to an HTTP response. Deliberately
// a plain class with no imports, so the pure logic above can throw it too
// and the unit tests can assert on `.status`/`.code` without touching the
// network-facing `_guard.ts`.
export class HttpError extends Error {
  status: number;
  code: string;
  // Optional structured fields merged into the JSON error body by handle()
  // (e.g. `{ order_id }` on 409 'table_busy' — contract §4: "mesa ocupada ->
  // 409 table_busy con order_id existente"). Never overrides `error`/`code`
  // even if a caller's `extra` happens to carry those keys.
  extra?: Record<string, unknown>;
  constructor(status: number, code: string, message: string, extra?: Record<string, unknown>) {
    super(message);
    this.status = status;
    this.code = code;
    this.extra = extra;
  }
}

// ---- Money helpers (plan-tecnico.md §5: money is integer centavos, only
// the server computes it). Kept here — not in src/lib/money.js — because
// these are the ones the *_logic.ts of each feature agent will reuse to
// validate/sum amounts server-side, and that file must stay import-free too.

/** True for a value that is safe to store/compare as an integer centavos amount. */
export function isValidCents(value: unknown): value is number {
  return typeof value === 'number' && Number.isInteger(value) && Number.isFinite(value) && value >= 0;
}

/** Sums an array of integer-centavos amounts, throwing on anything invalid. */
export function sumCents(values: number[]): number {
  return values.reduce((total, v) => {
    if (!isValidCents(v)) throw new HttpError(400, 'invalid_amount', 'Monto inválido');
    return total + v;
  }, 0);
}

/** unit_price (cents) * qty, rounded to the nearest centavo (qty may be fractional, e.g. granel by weight). */
export function lineTotalCents(unitPriceCents: number, qty: number): number {
  if (!isValidCents(unitPriceCents)) throw new HttpError(400, 'invalid_amount', 'Precio inválido');
  if (typeof qty !== 'number' || !Number.isFinite(qty) || qty <= 0) {
    throw new HttpError(400, 'invalid_qty', 'Cantidad inválida');
  }
  return Math.round(unitPriceCents * qty);
}

export function pesosToCents(pesos: number): number {
  return Math.round(pesos * 100);
}

export function centsToPesos(cents: number): number {
  return cents / 100;
}

// ---- Cost redaction (D7, entrega-1-contratos.md §4/§6b) ----
//
// `OrderItem.unit_cost` is frozen server-side at addItems time and RLS
// already blocks direct reads of it to non-platform callers
// (OrderItem.jsonc: `properties.unit_cost.rls.read`), but every `orders`/
// `stations` handler that RETURNS an OrderItem row does so through the
// function's own JSON response, which RLS never touches — a handler that
// forgets to redact hands `unit_cost` to every caller regardless of
// `Menú:ver_costos`, exactly like `catalog.listProducts` already guards
// against for `Product.cost`/`variants[].cost`. These two pure helpers are
// the one place that redaction logic lives, so every handler that returns
// OrderItem row(s) calls `hasPermission(ctx, 'Menú:ver_costos')` once and
// pipes its result (row or row[]) through here before responding.

/** Removes `unit_cost` from a single OrderItem-shaped row unless `canSeeCosts`. */
export function redactItemCost<T extends Record<string, unknown>>(row: T, canSeeCosts: boolean): T {
  if (canSeeCosts || row == null) return row;
  const { unit_cost: _unit_cost, ...rest } = row;
  return rest as T;
}

/** Array variant of {@link redactItemCost}. */
export function redactItemCosts<T extends Record<string, unknown>>(rows: T[], canSeeCosts: boolean): T[] {
  if (canSeeCosts) return rows;
  return rows.map((row) => redactItemCost(row, canSeeCosts));
}
